- name: variables from play level #Name can be given anything
  hosts: localhost
  vars: 
    PERSON: "Nanda"
    WISHES: "Morning from play"
  tasks:
  - name: check variables
    vars:
      PERSON: "Nanda from task"
      WISHES: "Morning from task"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"
# 1.cmd
# 2.task
# 3.file
# 4.prompt
# 5.play
# 6.inventory
# 7.roles