- name: conditions
  hosts: localhost
  tasks: 
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: user #user is variable name
    ignore_errors: true # ansible will not get exist even it got error 

  - name: print variable value
    ansible.builtin.command:
      msg: "User otput is: {{user}}"